spring: 
  application: 
    name: gatewayservicve
  cloud:
    gateway:
      routes:
        - id: ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderfallback
        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentfallback
            
eureka:
  instance:
     prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
   
server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000000000
            
            
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENTSERVICE/payment/dopayment